### ISSUE TITLE
ignore file extensions in directory? 

### ISSUE THREAD

**Issue by iquah1** [svenevs/exhale#161]
Hey there! 

Thanks for this amazing work. I recently integrated this into a project and I was REALLY happy with how it came out. I wanted to reach out to ask if there's a way to ignore certain file extensions? My use case is that I've got the following "structure"

```
src
    | - lib 
        | - f1.cpp
        | - f2.cpp
        | - readme.md

    | - include
        | - f1.h
        | - f2.h
        | - readme.md
```

where `readme.md` is a minimal file describing the contents of the directory. The hope is that users will be able to get a rough understanding of what is happening in the `readme.md` and within that `readme` we'll point to our `readthedocs` instance where they can get more information about a certain topic if that makes sense.

**Comment by svenevs** [comment]
> I was REALLY happy with how it came out

Thanks, glad to hear :slightly_smiling_face: 

I think I'm misunderstanding a bit, there's probably a configuration somewhere but which one (so many tools involved xD)?

If you wanted to exclude files from doxygen (and therefore prevent exhale from ever processing it), you would probably want to add to your doxygen configuration [`EXCLUDE`](https://www.doxygen.nl/manual/config.html#cfg_exclude) or [`EXCLUDE_PATTERNS`](https://www.doxygen.nl/manual/config.html#cfg_exclude_patterns).

So either in the `Doxyfile` or in `exhaleDoxygenStdin`.

```py
import textwrap
exhale_args = {
    # ... required args ...
    "exhaleExecutesDoxygen": True,
    # just an example
    "exhaleDoxygenStdin": textwrap.dedent('''
        EXCLUDE_PATTERNS = *.cpp
    ''')
}
```

1. Is the `readme.md` per directory a part of the documentation build?  Or is just for navigating e.g., GitHub readme?  Like are you talking about the "doxygen documentation for the directory" [example](https://my-favorite-documentation-test.readthedocs.io/en/latest/api/dir_arbitrary.html#dir-arbitrary)?
2. Or are you asking how to have a separate project for say `include` and `src` rather than them both being in the same sphinx output? (there is just one RTD site?)

**Comment by iquah1** [comment]
Ahh, sorry, I mean that I just want to not have the `readme.md`s parsed and rendered is all. Thanks for asking to clarify!

**Comment by svenevs** [comment]
Ok then yeah you should be able to get doxygen to ignore them with `EXCLUDE` or `EXCLUDE_PATTERNS`, if you don't have success post your `conf.py` (or relevant section).

But actually, if you don't have other markdown files that you want doxygen to process (e.g., for `\page` or `\group` [group not supported in exhale]) you can also override the default [`FILE_PATTERNS`](https://www.doxygen.nl/manual/config.html#cfg_file_patterns).  Doxygen has a lot of configs

**Comment by iquah1** [comment]
Gotcha, thanks! 

..... How do I pass in arguments to the doxygen build when I don't have a `Doxyfile`? I tried searching for `EXCLUDE_PATTERNS` on the exhale docs but I didn't seem to find an example. Would it be in a key value for `exhale_args`? 

The file in question is [here](https://github.com/openfheorg/openfhe-development/blob/exhale/docs/conf.py)

**Comment by svenevs** [comment]
Brief comment from phone, sorry just left xD

https://github.com/openfheorg/openfhe-development/blob/exhale/docs/conf.py#L113

The configurations there with PREDEFINED are what go to doxygen, just add them in that string I think

If not I can take a closer look soon 🙂

**Comment by iquah1** [comment]
That worked! Thank you so so much!
