### ISSUE TITLE
Don't display private member classes

### ISSUE THREAD

**Issue by Time0o** [svenevs/exhale#46]
I'm not sure if this is an issue with breathe or exhale but by default private member classes (which are definitely not part of the API) are displayed in the API documentation, i.e. without enabling `:private-members:`.  To me this seems to be a bug, is there currently a way to disable this behaviour?

**Comment by svenevs** [comment]
Hmm. Smells like a bug with breathe. Let's talk more here first though. Is there a public link you can give me to the code?

If not include the relevant sections of `conf.py` (`exhale_args`, breathe configurations) and in particular your doxygen configuration. If you're using an actual `Doxyfile`, upload it to gist.github.com (since it's huge xD).

**Comment by Time0o** [comment]
My project is located here: https://github.com/Time0o/TUD_computational_group_theory, the Doxyfile is located at doxygen/Doxyfile. The sphinx `conf.py` is dynamically generated by CMake (which kind of sucks, I'll admit it), look at the toplevel CMakeLists.txt, line 133 following. Unfortunately I have just switched the hosted documentation to pure Doxygen, since it's basically empty anyways I'll try to host the exhale results at: https://time0o.github.io/TUD_computational_group_theory/ shortly.

**Comment by Time0o** [comment]
Thanks for the detailed response. I think you are right, my documentation build is very messy atm. It's good to know that this is not a general problem with exhale, I will try to clean things up in my project when I have the time and I assume the problem will just solve itself.
