### ISSUE TITLE
[Question] Can I modify the rst content output?

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [svenevs/exhale#65]
So far exhale is great at recreating the doxygen hierarchy and separate pages for my huge project. My only beef with it is I'd like to edit the Full API section. I do not need it to display Files in the project when I already have a file hierarchy tree. 

I'd also want to get rid of the "source" tab in my nav bar. 

Is this possible? Thanks!

**Comment by svenevs** [comment]
Writing a response in #64 about excluding files to keep it in one place.

> I'd also want to get rid of the "source" tab in my nav bar.

Can you clarify what this means?  A picture would be helpful, it could be one of a couple things, and also depends on your html theme ;)

Modifying the rst can be done, but I think we can get clever (see #64) to minimize the effort on your part.  So I'd like to discuss that there before showing you how to modify the rst content, primarily because whatever you do on this aspect will likely break if exhale makes changes.

**Comment by TheMaverickProgrammer** [comment]
https://battlenetwork.readthedocs.io/

If it is the theme, I'm not sure where in my .rst docs defaults I should edit to disable the nav link so the theme doesn't generate it.

**Comment by TheMaverickProgrammer** [comment]
The navbar is generated by the theme im using and does not use any root tdoc information to generate. This is a non issue with exhale.

**Comment by TheMaverickProgrammer** [comment]
Reopening to ask a new but similar question. I see the detailed documentation shows up in the File page for the class code and not in the Class page for a class.

Here's where my `brief` and detailed descriptions are hiding: [link
](https://battlenetwork.readthedocs.io/api/file__home_docs_checkouts_readthedocs.org_user_builds_battlenetwork_checkouts_latest_BattleNetwork_bnExplosion.h.html#file-home-docs-checkouts-readthedocs-org-user-builds-battlenetwork-checkouts-latest-battlenetwork-bnexplosion-h)

Here's where I expect them: [link](https://battlenetwork.readthedocs.io/api/classExplosion.html#exhale-class-classExplosion).

This is probably on par with the changes you're planning on making but I don't need the link at the top that says "defined in Filed bnExplosion.h". 

That page contains (to me) a bunch of useless information. And if I were to have a link like that I'd want it to be a page with just the `:programlisting:` here: [link](https://battlenetwork.readthedocs.io/api/program_listing_file__home_docs_checkouts_readthedocs.org_user_builds_battlenetwork_checkouts_latest_BattleNetwork_bnExplosion.h.html).

Thank you for your work on this

**Comment by svenevs** [comment]
https://github.com/TheMaverickProgrammer/battlenetwork/blob/b88e61faaf685fdea36d0bc143c1ab391ec8dd90/BattleNetwork/bnExplosion.h#L7

and

https://github.com/TheMaverickProgrammer/battlenetwork/blob/b88e61faaf685fdea36d0bc143c1ab391ec8dd90/BattleNetwork/bnExplosion.h#L10

are in direct conflict with each other.  You aren't actually telling doxygen what you think you are, that says "document this as a `class`" *and* "document this as a `file`".  [This is probably what you are looking for](https://exhale.readthedocs.io/en/latest/mastering_doxygen.html#associating-documentation-with-the-right-file), but it's worth mentioning that if you just _don't_ do it (don't even use `\class`), it usually works out good.  Like in those docs I said "I normally default to this", but you don't have to if you avoid `\class` altogether.

Happens all the time xD

> don't need the link at the top that says "defined in Filed bnExplosion.h".

Eventually the end-game is to allow users to have custom writers for every kind (`class`, `struct`, `define`, `function`, `file`, ... etc).  And a few extra customization points for the root library page.

I'd rathe rnot add a config variable to remove this because knowing where something is defined (so you know what file to `#include`) is useful to library consumers.  They used to show up in the breathe directive, but don't anymore.  What you can instead do is post-filter what exhale generates since this one is relatively easy for you to remove.

You just want to hook into the [sphinx source-read event](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-source-read).  Boiler plate (all in `conf.py`, that's important):

```py
def source_read(app, docname, source):
    lines = []
    for ln in source[0].splitlines():
        if not ln.startswith("- Defined in :ref:`"):
            lines.append(ln)

    source[0] = "\n".join(lines)

# called for you by sphinx
def setup(app):
    # tell sphinx to call that function for that event
    app.connect("source-read", source_read)
```

Un-tested but should be close.  Basically that's the name of the game for fine-tuned changes unfortunately.  That or fork and tune it to how you want.  If you do the post-filtering approach make a note somewhere to yourself of what version.  If any future patch releases before the writer interface happens break the filtering, you'll want to pin exhale to a specific version.

P.S. something like this 

> `Definition (/home/docs/checkouts/readthedocs.org/user_builds/battlenetwork/checkouts/latest/BattleNetwork/bnExplosion.h)`

generally means that whatever you told exhale `doxygenStripFromPath` and whatever `doxygen` actually got (if you are using a `Doxyfile`) are not the same.  It should probably just end up as `BattleNetwork/bnExplosion.h` or maybe `bnExplosion.h` depending on configs.

**Comment by TheMaverickProgrammer** [comment]
lots of useful info here. Yeah doxygen is very verbose. I'll make those changes asap.

Thanks for the snippet on post-processing. now if only I could see the entire source stub before processing maybe I could write some more modifications. :)
