### ISSUE TITLE
[doxygenfunction: Cannot find function] When header file function declaration comment out with DOXYGEN_SHOULD_SKIP_THIS

### ISSUE THREAD

**Issue by Visit-Learn** [svenevs/exhale#86]
Hi,

I am new for this tool, I am not sure that I can ask question here or not.
And currently I want to use this tool to generate document with following environment

**Test Environment**
doxygen  (1.8.16)
sphinx      (2.3.1)
breathe    (4.13.0)
exhale      (0.2.3)

And I found that when I use DOXYGEN_SHOULD_SKIP_THIS to deal with duplicate issue (same function name in header file and C source file), the function comment in the C source file cannot find. But the Doxygen web page still work.

**Header File**
```
#ifndef TEST_H
#define TEST_H

#ifdef __cplusplus
extern "C" {
#endif

#if !defined(DOXYGEN_SHOULD_SKIP_THIS)
char* at_test_action(void* data);
#endif // DOXYGEN_SHOULD_SKIP_THIS

#ifdef __cplusplus
}
#endif

#endif /* TEST_H */

```

**Source File**
```
/**
 * \brief Fills the data buffer
 * \param[in] data data buffer for content preparation
 * \return pointer to the data buffer
 **/
char* at_test_action(void* data)
{
    char* ptr = (char*) data;
  
    sprintf( ptr, "AT\r\n" );

    return ptr;
}
```
![image](https://user-images.githubusercontent.com/19858499/73522426-55ba6d00-4443-11ea-83b1-9f6b7fa7e61f.png)

How can I deal with it?
And my conf.py setting as following,
```
exhale_args = {
    # These arguments are required
    "containmentFolder":     "./api",
    "rootFileName":          "library_root.rst",
    "rootFileTitle":         "Library API",
    "doxygenStripFromPath":  "..",
    # Suggested optional arguments
    "createTreeView":        True,
    # TIP: if using the sphinx-bootstrap-theme, you need
    # "treeViewIsBootstrap": True,
    "exhaleExecutesDoxygen": True,
    "exhaleDoxygenStdin": textwrap.dedent('''
        EXTRACT_ALL = YES
        SOURCE_BROWSER = YES
        EXTRACT_STATIC = YES
        OPTIMIZE_OUTPUT_FOR_C  = YES
        HIDE_SCOPE_NAMES = YES
        QUIET = YES
        INPUT = ../include ../src
        FILE_PATTERNS = *.c *.h
        EXAMPLE_RECURSIVE = YES
        GENERATE_TREEVIEW = YES
        PREDEFINED += DOXYGEN_SHOULD_SKIP_THIS
    ''')
}
```
Thank you so much.

**Comment by svenevs** [comment]
Hi @Visit-Learn,

> I am new for this tool, I am not sure that I can ask question here or not.

Sorry for the delay, questions are welcome!  Development is slow right now though :S

This behavior seems to be a feature of `breathe`, I wasn't aware of this until now.  Apparently the `.. doxygenfunction` directive by default ignores source files.  They will [create a filter finder](https://github.com/michaeljones/breathe/blob/bc4b0982e299fe1325c67ab47e7432f6250f093d/breathe/renderer/filter.py#L1080) which ultimately [rage quits for implementation files](https://github.com/michaeljones/breathe/blob/bc4b0982e299fe1325c67ab47e7432f6250f093d/breathe/renderer/filter.py#L1072).

With your current setup, you would need to set [`breathe_implementation_filename_extensions`](https://breathe.readthedocs.io/en/latest/directives.html#confval-breathe_implementation_filename_extensions) to trick it into documenting the `.c` files the way you want in your `conf.py`:

```py
# example ... could also add '.h'
breathe_implementation_filename_extensions = []
```

That will succeed in building the docs.  Some notes:

1. By default, using the exhale stdin approach, `DOXYGEN_SHOULD_SKIP_THIS` is [already defined](https://exhale.readthedocs.io/en/latest/reference/configs.html#exhale.configs.DEFAULT_DOXYGEN_STDIN_BASE) in addition to `DOXYGEN_DOCUMENTATION_BUILD`.  It doesn't hurt to add it on that last line `PREDEFINED += DOXYGEN_SHOULD_SKIP_THIS`), but in this case it was a red herring ha!
2. You're kind of fighting the conventions here.  Typically documentation is added in the `.h` files, not in the `.c` files.  So, if it's possible and acceptable for your circumstances, the ideal scenario would be to avoid documenting C files at all.  `INPUT = ../include` and `FILE_PATTERNS = *.h` (though since your code base is separated, it seems you may not need to override `FILE_PATTERNS` -- just depends on what files you have where).  Doing this means that

    - You won't need to mess with `breathe_implementation_filename_extensions`
    - You don't need all this extra `#if !defined(DOXYGEN_DOCUMENTATION_BUILD)` everywhere.

Does that make sense?

**Comment by svenevs** [comment]
Going to close this as resolved, please re-open if the above suggestions didn't work!
