### ISSUE TITLE
Incompatiblity with RTD

### ISSUE THREAD

**Issue by Chrismarsh** [svenevs/exhale#89]
Following the instructions results in an error:
``AttributeError: module 'sphinx.domains.c' has no attribute 'CStructObject``

This is due to Read the Docs using version 1.8.5 of sphinx. As noted here
https://github.com/svenevs/exhale#exhale-version-compatibility-with-python-sphinx-and-breathe

the new versions of breathe drop support for Sphinx < 2.

It's sufficient to specify ``breathe<4.13.0`` in your requirements.txt

It would be good if this could be added to the Exhale documentation

**Comment by svenevs** [comment]
Thank you for reporting what fixed it for you!  On RTD it's your choice what version of python you use, there are [additional configuration values of worth](https://docs.readthedocs.io/en/stable/config-file/v2.html) to control other aspects of your build.  Long term, you will need to adopt python 3 in order to continue using this project.
